services:
  # nginx:
  #   depends_on:
  #     - client
  #     - server
  #   restart: always
  #   build: ./Nginx
  #   ports:
  #     - "3050:80"
  client:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./Client
    ports:
       - "4200:4200"
       - "49513:49513"
#      - "3000:3000"
#      - "443:443"
    volumes:
      - /app/node_modules
      - ./Client:/app
    depends_on:
      - server
  server:
    restart: always
    build: ./Server
    ports:
      - "5000:5000"
    volumes:
      - ./Server:/app
      - /app/node_modules
      - /app/build
    depends_on:
      - mongo
      - redis
  mongo:
    restart: always
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - ./MongoDB:/data/db
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
networks:
  default:
    name: tawproject
    external: true