services:
  client:
    restart: always
    build: ./Client
    ports:
      - "4200:4200"
      - "49153:49513"
    volumes:
      - /app/node_modules
      - ./Client:/app

  mongo:

  server:

networks:
  default:
    name: tawproject
    external: true